name: Build-dev

on:
  push:
    branches:
      - 'dev'

jobs:
  build-dev:
    runs-on: ubuntu-latest
    env:
      DASH_DIR: ./app/dashboard

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20 LTS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ${{ env.DASH_DIR }}/package-lock.json

      - name: Install dependencies
        working-directory: ${{ env.DASH_DIR }}
        run: npm ci

      - name: Build project
        working-directory: ${{ env.DASH_DIR }}
        run: VITE_BASE_API=/api/ npm run build -- --outDir=build --assetsDir=statics

      - name: Create 404.html
        working-directory: ${{ env.DASH_DIR }}
        run: cp ./build/index.html ./build/404.html

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            rebeccapanel/rebecca:${{ github.ref_name }}
            ghcr.io/ppouria/rebecca:${{ github.ref_name }}
